### ISSUE TITLE
Add recursive Sequence<View> to ViewGroup for recursive child looping

### ISSUE THREAD

**Issue by Edward608** [android/android-ktx#295] opened 2018-02-09 09:30 UTC
I know there is a pull request which get merged by providing `Sequence<View>` for ViewGroup, but it only returns the direct child of the viewGroup, I wonder if anyone found it useful to have a version that iterate recursively if child is a `ViewGroup`.

**Comment by JakeWharton** [comment] 2018-02-09 13:49
Dupe of #209. Let's keep discussion there. Actual use cases welcome.

**Closed by JakeWharton** 2018-02-09 13:49 UTC
