### ISSUE TITLE
Context extensions to see if networkk/wifi connection is available

### ISSUE THREAD

**Issue by mightyfrog** [android/android-ktx#307] opened 2018-02-10 14:19 UTC
```kotlin
inline fun Context.hasNetworkConnection(): Boolean {
    val cm = getSystemService(Context.CONNECTIVITY_SERVICE) as ConnectivityManager
    return cm.activeNetworkInfo?.isConnected ?: false
}

inline fun Context.hasWifiConnection(): Boolean {
    val cm = getSystemService(Context.CONNECTIVITY_SERVICE) as ConnectivityManager
    return cm.activeNetworkInfo?.let { it.type == ConnectivityManager.TYPE_WIFI } ?: false
}
```

**Comment by JakeWharton** [comment] 2018-02-10 14:21
Dupe of #160. Read my response there.

**Closed by JakeWharton** 2018-02-10 14:21 UTC
