### ISSUE TITLE
Density converters

### ISSUE THREAD

**Issue by iglaweb** [android/android-ktx#460] opened 2018-03-24 20:04 UTC
Frequent calls to metrics converters would be very helpful (extensions of Resources). 
px -> sp
px -> dp
sp -> px
dp -> px

**Comment by JakeWharton** [comment] 2018-03-24 20:05
Dupe of #132

**Comment by JakeWharton** [comment] 2018-03-24 20:05
Please add any missing functions around display unit conversion to that issue.

**Closed by JakeWharton** 2018-03-24 20:05 UTC

**Comment by iglaweb** [comment] 2018-03-25 09:12
Ready.
