### ISSUE TITLE
Intent Extras delegation

### ISSUE THREAD

**Issue by dovahkiin98** [android/android-ktx#399] opened 2018-03-05 16:49 UTC
I was wondering if something like this would be useful for others

```kotlin
inline fin <T> Activity.intentExtra(key: String, defaultValue: T) = lazy {
    when(T::class.java) {
        Int::class.java -> intent.getIntExtra(key, defaultValue) as T
        Float::class.java -> intent.getFloatExtra(key, defaultValue) as T
...
    }
}

//call:
val intExtra: Int by intentExtra("intExtra", 0)
```

Maybe something easier where you don't have to pass the key, but it's figured out by the field name.
Was thinking about the same implementation for savedInstanceState but couldn't find a way, anyone has an idea?

**Comment by JakeWharton** [comment] 2018-03-05 17:06
Dupe of #265. Please add your thoughts to that issue.

**Closed by JakeWharton** 2018-03-05 17:06 UTC
