### ISSUE TITLE
AdapterView on item selected listener

### ISSUE THREAD

**Issue by dovahkiin98** [android/android-ktx#494] opened 2018-04-12 09:00 UTC
This will make settings selection listener easier, and it's still safe for onNothingSelected

```kotlin
fun AdapterView<*>.setOnItemSelectedListener(listener: (view: View?, position: Int, id: Long) -> Unit) {
        onItemSelectedListener = object : AdapterView.OnItemSelectedListener {
            override fun onItemSelected(parent: AdapterView<*>, view: View?, position: Int, id: Long) =
                listener(view, position, id)

            override fun onNothingSelected(parent: AdapterView<*>) = listener(null, -1, 0)
        }
    }
```

**Comment by JakeWharton** [comment] 2018-04-12 16:34
Dupe of #470

**Closed by JakeWharton** 2018-04-12 16:34 UTC
