### ISSUE TITLE
JakeWharton.Kotterknife

### ISSUE THREAD

**Issue by daberni** [android/android-ktx#184] opened 2018-02-06 08:12 UTC
Any plans of including your "kotterknife" view binding delegations?

https://github.com/JakeWharton/kotterknife

I am very happy with those, at least for activities. Although they are not perfect for Fragments at the moment.

**Comment by Edward608** [comment] 2018-02-06 08:19
Dupe of #172

**Comment by jeksor** [comment] 2018-02-06 08:30
Why are you need it?
Just use the synthetic, what's it)
https://kotlinlang.org/docs/tutorials/android-plugin.html

**Comment by JakeWharton** [comment] 2018-02-06 13:15
Nope

**Closed by JakeWharton** 2018-02-06 13:15 UTC
