### ISSUE TITLE
appcompat-v7-27.1.1 build problems after switching to 1.0.0-alpha1

### ISSUE THREAD

**Issue by hoornet** [android/android-ktx#549] opened 2018-05-20 09:59 UTC
switching from 'androidx.core:core-ktx:0.3' to 'androidx.core:core-ktx:1.0.0-alpha1' created 2 build problems:
1)  error: resource android:attr/fontVariationSettings not found.
Message{kind=ERROR, text=error: resource android:attr/fontVariationSettings not found., sources=[C:\Users\someguy\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.1.1.aar\3c30e...5e37\res\values\values.xml:251:5-69], original message=, tool name=Optional.of(AAPT)}

2) 
error: resource android:attr/ttcIndex not found.
Message{kind=ERROR, text=error: resource android:attr/ttcIndex not found., sources=[C:\Users\someguy\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.1.1.aar\3c3...37\res\values\values.xml:251:5-69], original message=, tool name=Optional.of(AAPT)}

**Comment by JakeWharton** [comment] 2018-05-20 15:05
Dupe of #548.

You have to migrate all your support library deps to androidx and you have to compile against Android P.

**Closed by JakeWharton** 2018-05-20 15:05 UTC
